[project]
name = "desafio-etl-reutilizavel"
version = "0.1.0"
description = ""
authors = [
    {name = "mateus",email = "mateussilvamn18@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandera (>=0.32.1,<0.33.0)",
    "pandas (>=3.0.3,<4.0.0)",
    "fastparquet (>=2026.5.0,<2027.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
